# Generated by Django 4.2.30 on 2026-04-27 13:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import pulpcore.app.models.base
import pulpcore.app.models.fields
import pulpcore.app.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0150_taskschedule_task_kwargs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPlan',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField(unique=True)),
                ('state', models.TextField(choices=[('waiting', 'Waiting'), ('skipped', 'Skipped'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('canceling', 'Canceling')], default='waiting')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('error', models.JSONField(null=True)),
            ],
            options={
                'permissions': [('manage_roles_taskplan', 'Can manage role assignments on task plans')],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskPlanStep',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('index', models.PositiveIntegerField()),
                ('task_name', models.TextField()),
                ('task_args', pulpcore.app.models.fields.EncryptedJSONField(default=list)),
                ('task_kwargs', pulpcore.app.models.fields.EncryptedJSONField(default=dict)),
                ('reserved_resources', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('dispatched_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.task')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.taskplan')),
            ],
            options={
                'ordering': ('index',),
                'unique_together': {('plan', 'index')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='taskplan',
            name='current_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.taskplanstep'),
        ),
        migrations.AddField(
            model_name='taskplan',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.CASCADE, to='core.domain'),
        ),
    ]
