# Generated by Django 4.2.30 on 2026-04-27 13:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import pulpcore.app.models.base
import pulpcore.app.models.fields
import pulpcore.app.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0150_taskschedule_task_kwargs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField(unique=True)),
                ('state', models.TextField(choices=[('waiting', 'Waiting'), ('skipped', 'Skipped'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('canceling', 'Canceling')], default='waiting')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('error', models.JSONField(null=True)),
            ],
            options={
                'permissions': [('manage_roles_workflow', 'Can manage role assignments on workflows')],
                'default_permissions': ('add', 'change', 'view'),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('index', models.PositiveIntegerField()),
                ('task_name', models.TextField()),
                ('reserved_resources', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('dispatched_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.task')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.workflow')),
            ],
            options={
                'ordering': ('index',),
                'unique_together': {('workflow', 'index')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkflowTaskArg',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('value', pulpcore.app.models.fields.EncryptedJSONField(null=True)),
                ('arg_index', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('workflow_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_args', to='workflow.workflowtask')),
            ],
            options={
                'ordering': ('arg_index',),
                'unique_together': {('workflow_task', 'arg_index')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkflowTaskKwarg',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('value', pulpcore.app.models.fields.EncryptedJSONField(null=True)),
                ('kwarg_key', models.TextField()),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('workflow_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_kwargs', to='workflow.workflowtask')),
            ],
            options={
                'unique_together': {('workflow_task', 'kwarg_key')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='workflow',
            name='current_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowtask'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.CASCADE, to='core.domain'),
        ),
        migrations.AddConstraint(
            model_name='workflowtaskarg',
            constraint=models.CheckConstraint(condition=models.Q(('content_type__isnull', True), ('value__isnull', True), _connector='OR'), name='workflowtaskarg_value_ctype_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='workflowtaskkwarg',
            constraint=models.CheckConstraint(condition=models.Q(('content_type__isnull', True), ('value__isnull', True), _connector='OR'), name='workflowtaskkwarg_value_ctype_exclusive'),
        ),
    ]
