# Generated by Django 5.2.14 on 2026-06-01 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_upstreampulp_connect_timeout_and_more'),
        ('workflow', '0002_workflow_pulp_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='task_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.taskgroup'),
        ),
    ]
