# Generated by Django 5.2.13 on 2026-05-08 17:32

import django.db.models.deletion
import django_lifecycle.mixins
import pulpcore.app.models.base
import pulpcore.app.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_taskschedule_task_kwargs'),
        ('workflow', '0003_workflow_task_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackService',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField()),
                ('script', models.TextField()),
                ('pulp_domain', models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'permissions': [('manage_roles_callbackservice', 'Can manage role assignments on callback services')],
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'unique_together': {('pulp_domain', 'name')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkflowCallback',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('callback_type', models.TextField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('finished', 'Finished')])),
                ('callback_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_callbacks', to='workflow.callbackservice')),
                ('dispatched_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.task')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='workflow.workflow')),
            ],
            options={
                'unique_together': {('workflow', 'callback_service', 'callback_type')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
