# Generated by Django 5.2.15 on 2026-07-15 14:45

import django.db.models.deletion
import django_lifecycle.mixins
import pulpcore.app.models.base
import pulpcore.app.util
from django.db import migrations, models

# Move per-execution state onto WorkflowRun and repoint each workflow's schedule from
# execute_workflow at start_workflow_run. start_workflow_run reuses the schedule's existing
# workflow_pk kwarg, so rewriting only task_name revives pending ("waiting") schedules.
# Prior run history (completed/failed/in-flight) is dropped and not back-filled as WorkflowRun rows.
WORKFLOW_SCHEDULE_NAME_PREFIX = "pulp_workflow.workflow:"
OLD_TASK_NAME = "pulp_workflow.app.tasks.execute_workflow"
NEW_TASK_NAME = "pulp_workflow.app.tasks.start_workflow_run"


def rewrite_workflow_schedules(apps, schema_editor):
    """Point pending workflow schedules at start_workflow_run."""
    TaskSchedule = apps.get_model("core", "TaskSchedule")
    TaskSchedule.objects.filter(
        name__startswith=WORKFLOW_SCHEDULE_NAME_PREFIX,
        task_name=OLD_TASK_NAME,
    ).update(task_name=NEW_TASK_NAME)


def revert_workflow_schedules(apps, schema_editor):
    """Point workflow schedules back at execute_workflow."""
    TaskSchedule = apps.get_model("core", "TaskSchedule")
    TaskSchedule.objects.filter(
        name__startswith=WORKFLOW_SCHEDULE_NAME_PREFIX,
        task_name=NEW_TASK_NAME,
    ).update(task_name=OLD_TASK_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_taskschedule_task_kwargs'),
        ('workflow', '0004_callbackservice_workflowcallback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='current_task',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='error',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='state',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='task_group',
        ),
        migrations.RemoveField(
            model_name='workflowtask',
            name='dispatched_task',
        ),
        migrations.RemoveField(
            model_name='workflowcallback',
            name='dispatched_task',
        ),
        migrations.AddField(
            model_name='workflow',
            name='dispatch_interval',
            field=models.DurationField(null=True),
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.TextField(choices=[('waiting', 'Waiting'), ('skipped', 'Skipped'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('canceling', 'Canceling')], default='waiting')),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('error', models.JSONField(null=True)),
                ('current_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.task')),
                ('pulp_domain', models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
                ('task_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.taskgroup')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workflow.workflow')),
            ],
            options={
                'ordering': ('-pulp_created',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkflowRunCallback',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('dispatched_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.task')),
                ('workflow_callback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_callbacks', to='workflow.workflowcallback')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='workflow.workflowrun')),
            ],
            options={
                'unique_together': {('workflow_run', 'workflow_callback')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.RunPython(
            rewrite_workflow_schedules,
            reverse_code=revert_workflow_schedules,
            elidable=True,
        ),
    ]
