# Generated by Django 5.2.15 on 2026-07-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_workflowrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowcallback',
            name='callback_type',
            field=models.TextField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('finished', 'Finished')]),
        ),
    ]
